### PR TITLE
Specify domain

### PR DESCRIPTION
**Pull request by bakku**
Gives the plugin the ability to specify the **domain** with the cookie.
This way the cookie can be set across subdomains.

### CODE REVIEW

**Comment by krazyjakee** [comment]
Thanks, but bower and demo are not unneccessary.

**Comment by bakku** [comment]
These commits were for myself.
This is why I reverted them before creating a pull request.

The pull request only includes the changes to the plugin

**Comment by krazyjakee** [comment]
My apologies, I read the list in reverse order.

**Comment by krazyjakee** [comment]
Thank you for this!

**Pull request merged**
